### ISSUE TITLE
新功能建议：通过坐标定位到地图上的点

### ISSUE THREAD

**Issue by NoNormalCreeper** [anitabi/anitabi.cn-document#12]
有时，我们需要查询一个特定地点附近的巡礼地点，例如想要查看自己已经定好的旅行线路周边有哪些地点可以进行巡礼。
此时的操作方法通常是手动在巡礼地图上通过缩放与滑动找到对应的地点，再查看附近的巡礼地点，这样较为麻烦。

而我的构想是用户通过输入 Google 地图的坐标，就可以直接跳转定位到巡礼地图上的地点，便于寻找。

**Comment by itorr** [comment]
这是个常见需求！
在谷歌地图中浏览到指定位置后，可以复制当时的页面地址，到动画巡礼地图网页内虚空粘贴，地图会飞入到和谷歌地图一样的位置

**Comment by NoNormalCreeper** [comment]
感谢！之前没注意到这个用法。

**Comment by itorr** [comment]
是需要想办法找机会说明给大家的隐藏用法，如何传达好头疼（
首先要记得加入到帮助文档！

**Comment by itorr** [comment]
帮助文档对应 issue https://github.com/anitabi/navi.anitabi.cn/issues/1

**Comment by NoNormalCreeper** [comment]
> 是需要想办法找机会说明给大家的隐藏用法，如何传达好头疼（ 首先要记得加入到帮助文档！

我觉得可以在左上角搜索框里或搜索框下面注明一下，或者再支持在搜索框粘贴就可以。毕竟搜索框里说了可以搜索“城市、作品、**地标**”，那么能搜索位置也是很符合逻辑的。

**Comment by itorr** [comment]
> 看到有帖子更新通知了，于是来看看。 我觉得这个需求应该不仅限于Google地图的坐标，而是适用于所有经纬度吧。我猜，其他在线地图工具（yahoo maps、百度地图等）也应该是遵循同一套标准的吧？ 不够就是可能要考虑应对不同格式的字符串（单独拷贝/内含于url）。
> 
> 此外，我还想到，有没有可能请求用户许可，经用户授权后直接获得用户的GPS信息，让用户可以找到当前位置的周边的场景？

是这样，其他常见的地图 URL 也可以支持，不过对于圣地巡礼来说、现行能用且唯一实际算的上能用的地图也只有谷歌地图了，可能支持了其他的在线地图工具也意义不大，但万一呢，先支持个。

定位功能入口在地图的右下角最上面的定位按钮。
点击后会和用户申请定位权限，可以实地实时跟随移动。方便查看沿路的取景点~

**Comment by itorr** [comment]
> > 是需要想办法找机会说明给大家的隐藏用法，如何传达好头疼（ 首先要记得加入到帮助文档！
> 
> 我觉得可以在左上角搜索框里或搜索框下面注明一下，或者再支持在搜索框粘贴就可以。毕竟搜索框里说了可以搜索“城市、作品、**地标**”，那么能搜索位置也是很符合逻辑的。

这个好耶 感觉也可以有
