### ISSUE TITLE
邀请码

### ISSUE THREAD

**Issue by Yingl-1** [anitabi/anitabi.cn-document#42]
邀请码是什么

**Comment by itorr** [comment]
目前需要在前台提交足够数量的地标才会发放邀请码

**Comment by Sciroccogti** [comment]
> 目前需要在前台提交足够数量的地标才会发放邀请码

请问这个前台是指网页端直接提交吗？（感觉不太对）

**Comment by Yingl-1** [comment]
?












yingl
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月2日(周日) 晚上10:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [anitabi/anitabi.cn-document] 邀请码 (Issue #42)




  
目前需要在前台提交足够数量的地标才会发放邀请码
  
请问这个前台是指网页端直接提交吗？（感觉不太对）
